// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portifolio.Data;

namespace Portifolio.Migrations
{
    [DbContext(typeof(IAgendamentoDbContext))]
    [Migration("20210731001816_AgendamentoV03")]
    partial class AgendamentoV03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portifolio.Models.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraAge")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("Portifolio.Models.Motorista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CpfMot")
                        .HasColumnType("int");

                    b.Property<string>("DataNascimentoMot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailMot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompletoMot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefoneMot")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("Portifolio.Models.NotaFiscal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AgendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEmissaoNf")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinatarioNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotoristaID")
                        .HasColumnType("int");

                    b.Property<int>("NumeroNf")
                        .HasColumnType("int");

                    b.Property<double>("PesoNf")
                        .HasColumnType("float");

                    b.Property<string>("ProdutoNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemetenteNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerieNf")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNf")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AgendaId");

                    b.HasIndex("MotoristaID");

                    b.ToTable("NotaFiscal");
                });

            modelBuilder.Entity("Portifolio.Models.Veiculo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AgendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CapacidadeVeic")
                        .HasColumnType("float");

                    b.Property<string>("MarcaVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotoristaID")
                        .HasColumnType("int");

                    b.Property<string>("PlacaCarre1Veic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaCarre2Veic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AgendaId");

                    b.HasIndex("MotoristaID");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Portifolio.Models.NotaFiscal", b =>
                {
                    b.HasOne("Portifolio.Models.Agenda", null)
                        .WithMany("NotaFiscal")
                        .HasForeignKey("AgendaId");

                    b.HasOne("Portifolio.Models.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaID");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("Portifolio.Models.Veiculo", b =>
                {
                    b.HasOne("Portifolio.Models.Agenda", "Agenda")
                        .WithMany()
                        .HasForeignKey("AgendaId");

                    b.HasOne("Portifolio.Models.Motorista", null)
                        .WithMany("Veiculo")
                        .HasForeignKey("MotoristaID");

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("Portifolio.Models.Agenda", b =>
                {
                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("Portifolio.Models.Motorista", b =>
                {
                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
