// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portifolio.Data;

namespace Portifolio.Migrations
{
    [DbContext(typeof(IAgendamentoDbContext))]
    partial class AgendamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portifolio.Models.Motorista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CpfMot")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNascimentoMot")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailMot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompletoMot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeiculoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("Portifolio.Models.NotaFiscal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEmissaoNf")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinatarioNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotoristaID")
                        .HasColumnType("int");

                    b.Property<int>("NumeroNf")
                        .HasColumnType("int");

                    b.Property<double>("PesoNf")
                        .HasColumnType("float");

                    b.Property<string>("ProdutoNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemetenteNf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerieNf")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeiculoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MotoristaID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("NotaFiscal");
                });

            modelBuilder.Entity("Portifolio.Models.Veiculo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapacidadeVeic")
                        .HasColumnType("float");

                    b.Property<string>("MarcaVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaCarre1Veic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaCarre2Veic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Portifolio.Models.Motorista", b =>
                {
                    b.HasOne("Portifolio.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoID");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Portifolio.Models.NotaFiscal", b =>
                {
                    b.HasOne("Portifolio.Models.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaID");

                    b.HasOne("Portifolio.Models.Veiculo", null)
                        .WithMany("NotaFiscal")
                        .HasForeignKey("VeiculoID");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("Portifolio.Models.Veiculo", b =>
                {
                    b.Navigation("NotaFiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
